openapi: '3.0.2'
info:
  title: ngobrol
  description: ngobrol yuk.
  version: '1.0.0'
servers:
  - url: http://localhost:4500
    description: local
security:
  - Key: []
    Secret: []
paths:
  /health_check:
    get:
      summary: Health Check
      description: checking service and all dependencies is up and running
      tags:
        - system
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                data: []
                response_code: "000000"
                response_desc:
                  id: ""
                  en: ""
                meta:
                  version: "v1.0.0"
                  api_status: "stable"
                  api_env: "local"
        500:
          description: Something error on the internal service
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              examples:
                DBError:
                  value:
                    data: []
                    response_code: "101001"
                    response_desc:
                      id: "Error koneksi ke Database"
                      en: "Database connection error"
                    meta:
                      version: "v1.0.0"
                      api_status: "stable"
                      api_env: "local"
                CacheError:
                  value:
                    data: []
                    response_code: "101002"
                    response_desc:
                      id: "Error koneksi ke Cache server"
                      en: "Cache connection error"
                    meta:
                      version: "v1.0.0"
                      api_status: "stable"
                      api_env: "local"
                InfluxError:
                  value:
                    data: []
                    response_code: "101003"
                    response_desc:
                      id: "Error koneksi ke Influx"
                      en: "Influx connection error"
                    meta:
                      version: "v1.0.0"
                      api_status: "stable"
                      api_env: "local"
  /api/v1/messages:
    get:
      summary: List all messages
      operationId: listMessages
      tags:
        - message
      responses:
        '200':
          description: A paged array of messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                data:
                  - id: "f33e861d-0241-405c-b58c-d4416a772f0a"
                    message: "Hello"
                    created_at: "2020-05-08T05:14:31.489226+07:00"
                    updated_at: "2020-05-08T05:14:31.489226+07:00"
                  - id: "f33e861d-0241-405c-b58c-d4416a772f0b"
                    message: "World"
                    created_at: "2020-05-08T05:15:31.489226+07:00"
                    updated_at: "2020-05-08T05:15:31.489226+07:00"
                response_code: "000000"
                response_desc:
                  id: ""
                  en: ""
                meta:
                  version: "v1.0.0"
                  api_status: "stable"
                  api_env: "local"
    post:
      tags:
        - "message"
      summary: "Add a new message"
      description: ""
      operationId: "addMessage"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              example:
                data:
                  - id: "f33e861d-0241-405c-b58c-d4416a772f0b"
                    message: "Hallo"
                    created_at: "2020-05-08T05:14:31.489226+07:00"
                    updated_at: "2020-05-08T05:14:31.489226+07:00"
                response_code: "000000"
                response_desc:
                  id: ""
                  en: ""
                meta:
                  version: "v1.0.0"
                  api_status: "stable"
                  api_env: "local"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              example:
                response_code: "101004"
                response_desc:
                  id: "Bad Request"
                  en: "Bad Request"
                meta:
                  version: "v1.0.0"
                  api_status: "stable"
                  api_env: "local"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"

components:
  schemas:
    MessageRequest:
      type: "object"
      required:
        - "message"
      properties:
        message:
          type: "string"
          example: "Hello"
    BaseResponse:
      type: object
      description: health check responses
      required:
        - response_code
        - response_desc
        - meta
      properties:
        data:
          type: array
          description: empty
          items:
            type: object
        response_code:
          type: string
          description: 6 digits response code
        response_desc:
          description: description of response code
          type: object
          properties:
            id:
              type: string
            en:
              type: string
        meta:
          type: object
          properties:
            version:
              type: string
            api_status:
              type: string
            api_env:
              type: string
